#!/usr/bin/env bash

# Prints all 256 colors that are available on tmux.
# I don't remember where I found this code snippet...

for i in {0..255}; do
	printf "\x1b[38;5;${i}mcolour${i}\x1b[0m "
	[[ $(($i % ${1:-2})) == 0 ]] && printf "\n"
done
