#!/usr/bin/bash
#
# A simple trashing program I made

# Create the trashx directory if it doesn't exist
[[ -r "$HOME/.trashx" ]] || mkdir "$HOME/.trashx"

# Commands:
case "$1" in

	# List the items in trash
	"-l")
			
			(cd "$HOME/.trashx" && ls -hslA)
			;;
		
	# Clear the trash
	"-c")
			
			local choice=
			printf "%s" "Are you sure you want to clear the trash? "
			
			while [[ 0 ]]; do

					printf "%s\n%s" "(y=yes / n=no / l|ls=list)" "choice> "
					read choice
					
					case "${choice}" in
							
							"Y"|"y")
									
									rm -rf "${HOME}/.trashx/"
									mkdir "${HOME}/.trashx/"
																			
									break
									;;
							
							"N"|"n")
									
									break
									;;
							
							"L"|"l"|"ls")
									
									(cd "${HOME}/.trashx" && ls -hslA)
									;;
							
							*)
									
									echo "trashx: -l: ${choice}: invalid choice"
									return 1
									
					esac
					
			done
			;;

	# Trash, move, delete... all the same thing
	"-t"|"-m"|"-d")

			for item in "${@:2}"; do
					mv "${item}" -t "${HOME}/.trashx/"
			done

			;;
			
	
	# Help
	*)
			
			echo "trashx: no arguments found"
			echo "  Options:"
			echo "    -l    List all trashed files"
			echo "    -c    Clear the trash"
			echo "    -t\\"
			echo "    -m\\   Move one or more files/directories to the trash."
			echo "    -d"
			
			;;
			
esac
