#!/usr/bin/env bash

# Define Default Prompt
if [[ "$WD_Platform" == "wsl" ]]; then WD_DefaultPrompt=0
elif [[ "$WD_Platform" == "regular" ]]; then WD_DefaultPrompt=1
elif [[ "$WD_Platform" == "termux" ]]; then WD_DefaultPrompt=2
else WD_DefaultPrompt=0; fi

# Set the choice
if [[ -z $1 ]]; then
	[[ "$1" != "$WD_DefaultPrompt" ]] \
	&& Choice=$WD_DefaultPrompt \
	|| Choice=2
else
	Choice=$1
fi

# Set the prompts
if [[ $Choice == 0 ]]; then
		PS1='\[$(if [[ $? == 0 ]]; then echo \033[36m; else echo \033[31m; fi)\][\!] \[\033[01;32m\]\u@$(hostname | cut -c-5)\[\033[m\]:\[\033[01;34m\]\w\[\033[m\]$ '
elif [[ $Choice == 1 ]]; then
		PS1='\[$(if [[ $? == 0 ]]; then echo \033[36m; else echo \033[31m; fi)\][\!] \[\033[01;34m\]\w\[\033[m\]$ '
elif [[ $Choice == 2 ]]; then
		topDirs='$(basename "$(cd .. && echo $PWD)")/$(basename $PWD)'
		PS1='\
\[$(if [[ $? == 0 ]]; then echo \033[36m; else echo \033[31m; fi)\][\!] \
\[\033[01;34m\]$(echo '"${topDirs}"')\
\[\033[m\]$ '
else
		echo "Invalid prompt argument: $1"
		exit 1
fi
