" Vim Test File
" Author: YohananDiamond
" Repository: https://github.com/YohananDiamond/dotfiles

""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set nocompatible
execute pathogen#infect()

" Initial Variables
let g:Config = {}
let g:Config.InitPath = resolve(expand('<sfile>:p:h'))

" Set up import and reload commands
command! -nargs=1 Import
    \ if isdirectory('C:\') | let s:extra = '/vimfiles' | else | let s:extra = '' | endif |
	\ exec 'source ' . g:Config.InitPath . s:extra . "/" . eval(<f-args>) . '.vim'
command! -nargs=0 Reload
	\ source $MYVIMRC

" GUI or not
if has('gui_running')
    set guioptions=agit

    if !isdirectory('C:\')
        let &guifont='Fixedsys 9,Ubuntu Mono 12,Fira Code 10.5,Cascadia Code 10.5,Consolas 12,Monospace 12'
    else
        let &guifont='Ubuntu Mono:h12.5,Fira Code:h10.5,Cascadia Code:h10.5,Consolas:h12,monospace:h12'
    endif
endif

" Set status line settings (when not using lightline)
if isdirectory('C:\')
    set statusline=\ %f
    set statusline+=%=
    set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
    set statusline+=\ [%{&fileformat}\]\ 
    set statusline+=\ %p%%\ 
    set statusline+=\ %l:%c
    set statusline+=\ 
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" <Editor settings & etc.>

syntax on
set backspace=indent,eol,start
set laststatus=2 " Enable status bar
set number relativenumber " Hybrid numbers on the left edge of the screen
set encoding=utf-8
set textwidth=0 wrapmargin=0 " Prevent physical linebreak
set wildmode=longest,list " Bash-like command completion
set hidden " Prevent quitting vim with :q & etc.
set autoindent " For keeping the same indentation level on new liens
set hlsearch incsearch " Highlight & increment
set virtualedit=
set display+=lastline
set linebreak
set wrap
set cursorline
set mouse=a " Enable mouse

" Commands
command! -nargs=0 WhitespaceMode set list!
command! -nargs=0 WrapMode set wrap!
command! -nargs=0 GitSync !echo "Syncing..." && git pull && git add . && git commit && git push

" Listchars
set listchars=tab:»\ 
set listchars+=space:·
set listchars+=extends:%
set listchars+=precedes:%
set listchars+=eol:$,
set listchars+=trail:~

filetype plugin indent on " Idk what is this but it seems to work.

" Set color theme
set background=dark
colorscheme gruvbox

" Autocmds
autocmd BufNewFile,BufRead,BufEnter *.mq :set filetype=mq 
autocmd FileType mq :call OptSpaceIndentation(2) 
autocmd FileType mq :nnoremap <buffer><silent> <Leader>c I\# <esc>A #/<esc>
autocmd FileType python :nnoremap <buffer><silent> <Leader>c I#<esc>
autocmd FileType vim :nnoremap <buffer><silent> <Leader>c I"<esc>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" <Option Functions>

" Create function to set tab indentation
func! OptTabIndentation(size)
	let &tabstop=a:size
	let &shiftwidth=a:size
	set noexpandtab
endfunction

" Create function to set space indentation
func! OptSpaceIndentation(size)
	let &tabstop=a:size
	let &shiftwidth=a:size
	set expandtab
	set softtabstop=0
	set smarttab
endfunction

"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" <Functions>

func! XReplace(...)
    let l:a = input('Replace> ')
    let l:b = input('Replace /' . l:a . '/ with> ')
    let l:c = input('One by one? [Y/n] ')
    if (l:c == 'Y') || (l:c == 'y')
        let l:mode = 'gc'
    elseif (l:c == 'N') || (l:c == 'n')
        let l:mode = 'g'
    else
        let l:mode = 'g'
    endif
    exec '%s/' . l:a . '/' . l:b . '/' . l:mode
endfunc
command! -nargs=0 XReplace call XReplace()

"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" <Keymappings>

let mapleader = ' '

" Switch between buffers
nnoremap <silent> <C-x>j :bn<CR>
nnoremap <silent> <C-x>k :bp<CR>
tnoremap <silent> <C-x>j <C-w>:bn<CR>
tnoremap <silent> <C-x>k <C-w>:bp<CR>
nnoremap <silent> <C-x><Down> :bn<CR>
nnoremap <silent> <C-x><Up> :bp<CR>
tnoremap <silent> <C-x><Down> <C-w>:bn<CR>
tnoremap <silent> <C-x><Up> <C-w>:bp<CR>

" Mouse Wheel Scrolling
map <ScrollWheelUp> <C-U>
map <ScrollWheelDown> <C-D>

" Select all
nnoremap <silent> <space>a ggVG
vnoremap <silent> <space>a <Esc>ggVG

" Copy to registers
nnoremap <silent> <space>y "+y
nnoremap <silent> <space>p "+p
nnoremap <silent> <space>x "+x
vnoremap <silent> <space>y "+y
vnoremap <silent> <space>p "+p
vnoremap <silent> <space>x "+x

" Move by graphical, not physical line
" nnoremap <silent> <Up> gk
" nnoremap <silent> <Down> gj
" vnoremap <silent> <Up> gk
" vnoremap <silent> <Down> gj
" nnoremap <silent> <End> g<End>
" nnoremap <silent> <Home> g<Home>
" vnoremap <silent> <End> g<End>
" vnoremap <silent> <Home> g<Home>

" Indentation Management
nnoremap <silent> <Tab> >>
nnoremap <silent> <S-Tab> <<
vnoremap <silent> <Tab> >gv
vnoremap <silent> <S-Tab> <gv

" Plugin-related
nnoremap <silent> <C-x>n :NERDTreeToggle<CR>

" Close windows
nnoremap <silent> <C-x>0 :close<CR>

" Clear search query
nnoremap <silent> <space>/ :noh<CR>

" Kill buffers
nnoremap <silent> <C-x>k :b#<bar>bd#<CR>

" Folding Commands
nnoremap <silent> <space><right> zO
nnoremap <silent> <space><left> zm
nnoremap <silent> <space>l zO
nnoremap <silent> <space>h zm

" Use ç/Ç (from Portuguese/Brazilian keyboard) on normal mode for :
nmap Ç :
nmap ç ;

""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" <Plugin Settings>

" Lightline
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'readonly', 'filename' ] ],
      \ }}

" Space Indentation
call OptSpaceIndentation(4)
